# wrangler.toml (repo root)
name = "mplcompiler-pages"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

# SvelteKit adapter-cloudflare (Pages) output
pages_build_output_dir = ".svelte-kit/cloudflare"

# ===== Production (default) bindings =====
# This makes your D1 database available as platform.env.DB in Pages Functions.
[[d1_databases]]
binding = "DB"         # MUST match your code: platform.env.DB
database_name = "db"   # the D1 database's name
database_id = "3a16b3cd-f777-4572-99c7-3a1b9274e526"  # from `wrangler d1 list`

# Optional plain vars for local/dev deploys via wrangler.
# Don't commit real secrets here for public repos.
[vars]
# PARSER_URL = "https://inventory-pdf-parser.fly.dev/parse"
# PARSER_TOKEN = "Bearer <token>"

# ===== Preview environment bindings =====
# If you want PREVIEW deploys (PR builds) to have bindings too,
# repeat the binding for the preview env (can be the same DB or a different one).
[env.preview]

[[env.preview.d1_databases]]
binding = "DB"
database_name = "db"
database_id = "3a16b3cd-f777-4572-99c7-3a1b9274e526"

[env.preview.vars]
# PARSER_URL = "https://inventory-pdf-parser.fly.dev/parse"
# PARSER_TOKEN = "Bearer <token>"
